// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGtcf5gnZR8zsos5Dup0TqD7iIdJR3JAU',
    appId: '1:240706963760:web:b8274148b83ba13cf6e0f5',
    messagingSenderId: '240706963760',
    projectId: 'firestore-33883',
    authDomain: 'firestore-33883.firebaseapp.com',
    storageBucket: 'firestore-33883.firebasestorage.app',
    measurementId: 'G-SGTQKGYKLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfoMaJj3Fz_eO4-GXHwuptlM-n3Eu5-o8',
    appId: '1:240706963760:android:9436ee212b361339f6e0f5',
    messagingSenderId: '240706963760',
    projectId: 'firestore-33883',
    storageBucket: 'firestore-33883.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGtcf5gnZR8zsos5Dup0TqD7iIdJR3JAU',
    appId: '1:240706963760:web:3dae36c6d02f9802f6e0f5',
    messagingSenderId: '240706963760',
    projectId: 'firestore-33883',
    authDomain: 'firestore-33883.firebaseapp.com',
    storageBucket: 'firestore-33883.firebasestorage.app',
    measurementId: 'G-F2S0SJC39F',
  );

}